### ISSUE TITLE
Fix problem stopwatch-View being reset, when swiped to the far right

### ISSUE THREAD

**Issue by terle** [terle/NoitsoHinterBahnApp#2]

**Comment by darwind** [comment]
Problem is that when swiping to the last Fragment (LeaderBoardFragment) the state of the StopwatchFragment is lost. Also how should we handle the stopwatch ticking along?

**Comment by darwind** [comment]
Move the stopwatch to a Service (http://developer.android.com/reference/android/app/Service.html). This way the stopwatch will tick along even though we've switched to another Fragment. Also the state of the buttons and textfields can be saved in a SharedPreference or in the Service. The is exactly what it implies - a service that runs in the background.
