### ISSUE TITLE
Play "Eye of the Tiger" when starting

### ISSUE THREAD

**Issue by terle** [terle/NoitsoHinterBahnApp#6]
When the start button is pressed for the first time. The first few seconds of "Eye of the Tiger" could be played as motivation

**Comment by darwind** [comment]
Better yet, set your own music as startup ;-)

Maybe just create a button on the actionbar for settings?

**Comment by darwind** [comment]
Should be enabled through a settings menu or something - at least it should be possible to disable it ;-)

**Comment by terle** [comment]
Not able to select wheter it is enabled or diable.
I'll make another issue and close this one
